<?php
// this include file is generated by Composer, and sets up autoloading of
// our classes - https://www.php.net/manual/en/language.oop5.autoload.php
require 'vendor/autoload.php';

// This initialized the DotENV library- it reads in the .env file, and
// builds a global $_ENV array with our settings
$dotenv = Dotenv\Dotenv::createImmutable(__DIR__);
$dotenv->load();

// This starts a PHP session - https://www.php.net/manual/en/book.session.php
session_start();

/**
 * Begin coding!
 */